// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-portfolio-items.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-portfolio-items.ts
var list_portfolio_items_default = defineTool({
  name: "list_portfolio_items",
  title: "List portfolio items",
  description: "List portfolio items from the photography site, newest first by display order.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of items to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("portfolio_items").select("id,title,description,category,image_url,display_order,created_at").order("display_order", { ascending: true }).limit(limit ?? 20);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-portfolio-item.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var create_portfolio_item_default = defineTool2({
  name: "create_portfolio_item",
  title: "Create portfolio item",
  description: "Add a new portfolio item to the photography site (admin only).",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Title of the portfolio item."),
    image_url: z2.string().url().describe("Public URL of the image."),
    description: z2.string().trim().nullable().describe("Optional description."),
    category: z2.string().trim().nullable().describe("Optional category."),
    display_order: z2.number().int().nullable().describe("Optional sort position.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, image_url, description, category, display_order }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("portfolio_items").insert({
      title,
      image_url,
      description: description ?? null,
      category: category ?? null,
      display_order: display_order ?? null
    }).select();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { item: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/list-gallery-images.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_gallery_images_default = defineTool3({
  name: "list_gallery_images",
  title: "List gallery images",
  description: "List gallery images from the photography site.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(20).describe("Maximum number of images to return."),
    category: z3.string().trim().nullable().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("gallery_images").select("id,image_url,alt_text,category,display_order,created_at").order("display_order", { ascending: true }).limit(limit ?? 20);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { images: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-experience-entries.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_experience_entries_default = defineTool4({
  name: "list_experience_entries",
  title: "List experience entries",
  description: "List the photographer's experience/timeline entries.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).default(50).describe("Maximum number of entries to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("experience_entries").select("id,year,title,description,display_order").order("display_order", { ascending: true }).limit(limit ?? 50);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-contact-messages.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_contact_messages_default = defineTool5({
  name: "list_contact_messages",
  title: "List contact messages",
  description: "List contact form messages received by the site (admin only).",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).default(20).describe("Maximum number of messages to return."),
    only_unread: z5.boolean().default(false).describe("Return only unread messages.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, only_unread }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contact_messages").select("id,name,email,message,is_read,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (only_unread) query = query.eq("is_read", false);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rffnmyfvrxulwfwuovru";
var mcp_default = defineMcp({
  name: "code-converter-hub",
  title: "Code Converter Hub",
  version: "0.1.0",
  instructions: "Tools for the KNOXS photography site. Read and manage portfolio items, gallery images, experience entries, and contact messages as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_portfolio_items_default,
    create_portfolio_item_default,
    list_gallery_images_default,
    list_experience_entries_default,
    list_contact_messages_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
